openapi: 3.0.2

info:
  version: 0.0.1
  title: Jarless API

servers:
  - url: http://localhost:5000
    description: Local

paths:

  /version:
    get:
      operationId: jarless.api.api_version
      summary: Retorna a versão da API
      responses:
        200:
          description: Success

  /executions/{package}:
    parameters:
      - name: package
        in: path
        description: Package
        required: true
        schema:
          type: string
    post:
      operationId: jarless.api.executions.create_execution
      summary: Create a new execution
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                inputs:
                  additionalProperties: true
                  nullable: true
      responses:
        201:
          description: Created

  /executions/{package}/{task_id}/add/output:
    parameters:
      - name: package
        in: path
        description: Package
        required: true
        schema:
          type: string
      - name: task_id
        in: path
        description: Task ID
        required: true
        schema:
          type: string
      - name: secrets
        in: query
        description: Permission
        schema:
          type: string

    post:
      operationId: jarless.api.executions.add_output
      summary: Add an output for a given task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: output1
                value:
                  type: string
                  example: value1
                  nullable: true
                filedata:
                  type: string
                  format: binary
                  nullable: true
      responses:
        201:
          description: Added
